make main.yaml fail

diff --git a/main.yaml b/main.yaml
--- a/main.yaml
+++ b/main.yaml
@@ -13,7 +13,7 @@ jobs:
         run: echo "Hello, CI/CD!"
 
       #- name: Simulate an error
-      #  run: echo "About to fail" ; exit 1
+       run: echo "About to fail" ; exit 1
 
       - name: Another greeting
         run: echo "Hello, CI/CD again!"
